version: '3.2'
services:
  db:
    image: postgres:13.7-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: customers,transactions
    volumes:
      - ./script:/docker-entrypoint-initdb.d
